src/Entity/Person.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use App\Repository\PersonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PersonRepository::class)]
#[ApiResource(
	operations: [
		new Get(),
		new GetCollection(),
		new Post(security: 'is_granted("ROLE_ADMIN")'),
		new Put(security: 'is_granted("ROLE_ADMIN")'),
		new Patch(security: 'is_granted("ROLE_ADMIN")'),
		new Delete(security: 'is_granted("ROLE_ADMIN")'),
	],
	formats: [
		'jsonld',
		'json',
		'html',
		'csv' => 'text/csv',
	],
	normalizationContext: [
		'groups' => ['person:read'],
	],
	denormalizationContext: [
		'groups' => ['person:write'],
	],
	paginationItemsPerPage: 10,
)]
class Person
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['person:read', 'person:write', 'assignment:read', 'repeatedAssignment:read'])]
    private ?int $id = null;

	#[ORM\Column(length: 255)]
	#[Groups(['person:read', 'person:write', 'assignment:read', 'repeatedAssignment:read'])]
	#[Assert\NotBlank]
	private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Groups(['person:read', 'person:write', 'assignment:read', 'repeatedAssignment:read'])]
    #[Assert\NotBlank]
    private ?string $lastName = null;

	/**
	 * @var Collection<int, Assignment>
	 */
    #[ORM\OneToMany(mappedBy: 'person', targetEntity: Assignment::class, orphanRemoval: true)]
    #[Groups(['person:read', 'person:write'])]
    private Collection $assignments;

    #[ORM\Column(nullable: true)]
    private ?string $idExternal = null;

	/**
	 * @var Collection<int, RepeatedAssignment>
	 */
    #[ORM\OneToMany(mappedBy: 'person', targetEntity: RepeatedAssignment::class, orphanRemoval: true)]
    private Collection $repeatedAssignments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $jobTitle = null;

    public function __construct()
    {
        $this->assignments = new ArrayCollection();
        $this->repeatedAssignments = new ArrayCollection();
    }

	public function __toString(): string
	{
		return $this->getFullName();
	}

	public function getFullName(): string
	{
		return $this->firstName . ' ' . $this->lastName;
	}

    public function getId(): ?int
    {
        return $this->id;
    }

	public function getFirstName(): ?string
	{
		return $this->firstName;
	}

	public function setFirstName(string $firstName): static
	{
		$this->firstName = $firstName;

		return $this;
	}

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection<int, Assignment>
     */
    public function getAssignments(): Collection
    {
        return $this->assignments;
    }

    public function addAssignment(Assignment $assignment): static
    {
        if (!$this->assignments->contains($assignment)) {
            $this->assignments->add($assignment);
            $assignment->setPerson($this);
        }

        return $this;
    }

    public function removeAssignment(Assignment $assignment): static
    {
        if ($this->assignments->removeElement($assignment)) {
            // set the owning side to null (unless already changed)
            if ($assignment->getPerson() === $this) {
                $assignment->setPerson(null);
            }
        }

        return $this;
    }

    public function getIdExternal(): ?string
    {
        return $this->idExternal;
    }

    public function setIdExternal(?string $idExternal): static
    {
        $this->idExternal = $idExternal;

        return $this;
    }

    /**
     * @return Collection<int, RepeatedAssignment>
     */
    public function getRepeatedAssignments(): Collection
    {
        return $this->repeatedAssignments;
    }

    public function addRepeatedAssignment(RepeatedAssignment $repeatedAssignment): static
    {
        if (!$this->repeatedAssignments->contains($repeatedAssignment)) {
            $this->repeatedAssignments->add($repeatedAssignment);
            $repeatedAssignment->setPerson($this);
        }

        return $this;
    }

    public function removeRepeatedAssignment(RepeatedAssignment $repeatedAssignment): static
    {
        if ($this->repeatedAssignments->removeElement($repeatedAssignment)) {
            // set the owning side to null (unless already changed)
            if ($repeatedAssignment->getPerson() === $this) {
                $repeatedAssignment->setPerson(null);
            }
        }

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->jobTitle;
    }

    public function setJobTitle(?string $jobTitle): static
    {
        $this->jobTitle = $jobTitle;

        return $this;
    }
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Repository\AssignmentRepository;
use App\Repository\RepeatedAssignmentRepository;
use DateTimeZone;
use Exception;
use InvalidArgumentException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Exception\LogicException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PersonRepository;

class PersonController extends AbstractController
{
	private PersonRepository $personRepository;
	private AssignmentRepository $assignmentRepository;
	private RepeatedAssignmentRepository $repeatedAssignmentRepository;

	public function __construct(
		PersonRepository $personRepository,
		AssignmentRepository $assignmentRepository,
		RepeatedAssignmentRepository $repeatedAssignmentRepository,
	) {
		$this->personRepository = $personRepository;
		$this->assignmentRepository = $assignmentRepository;
		$this->repeatedAssignmentRepository = $repeatedAssignmentRepository;
	}

	#[Route('/person', name: 'app_person')]
	public function index(Request $request): Response
	{
		$searchTerm = $request->query->get('search', '');

		if (!is_string($searchTerm)) {
			throw new InvalidArgumentException('Search term is not a string');
		}

		$persons = $this->personRepository->search($searchTerm);

		return $this->render('person/show.html.twig', [
			'persons' => $persons,
			'search_term' => $searchTerm
		]);
	}

	/**
	 * @throws Exception
	 */
	#[Route('/person/{id}', name: 'app_person_detail')]
	public function show(int $id): Response
	{
		$person = $this->personRepository->find($id);

		if (!$person) {
			throw $this->createNotFoundException('No person found for id ' . $id);
		}

		$currentAssignments = $this->assignmentRepository->findCurrentlyOngoing($person);
		$currentRepeatedAssignments = $this->repeatedAssignmentRepository->findCurrentlyOngoing($person);

		if (count($currentAssignments) + count($currentRepeatedAssignments) > 1) {
			throw new LogicException('More assignments for one time for one person, should never be.');
		}

		// Set assignment to 'null' to say no assignment is currently active
		$assignment = false;
		$from = false;
		$to = false;

		if (count($currentAssignments) === 1) {
			$assignment = $currentAssignments[0];
			$from = $assignment->getFromDate()->setTimezone(new DateTimeZone('Europe/Prague'));
			$to = $assignment->getToDate()->setTimezone(new DateTimeZone('Europe/Prague'));
		}
		else if (count($currentRepeatedAssignments) === 1) {
			$assignment = $currentRepeatedAssignments[0];
			$from = $assignment->getFromTime();
			$to = $assignment->getToTime();
		}

		return $this->render('person/detail.html.twig', [
			'person' => $person,
			'currentAssignment' => $assignment,
			'from' => $from ? $from->format('H:i') : $from,
			'to' => $to ? $to->format('H:i') : $to,
		]);
	}
}

templates/person/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ person.fullName }}{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <div class="col-md-8 mt-2">
            <h2 class="font-weight-bold bg-light rounded mx-auto text-center" style="opacity: 0.9;">
	            {{ person.fullName }}
            </h2>
            <div class="table-responsive">
                <table class="modern-table">
                    <tbody>
                    <tr>
                        <th>ID</th>
                        <td>{{ person.id }}</td>
                    </tr>
                    <tr>
                        <th>First Name</th>
                        <td>{{ person.firstName }}</td>
                    </tr>
                    <tr>
                        <th>Last Name</th>
                        <td>{{ person.lastName }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{ person.email }}</td>
                    </tr>
                    <tr>
                        <th>Job Title</th>
                        <td>{{ person.jobTitle }}</td>
                    </tr>
                    <tr>
                        <th>Current status</th>
                        <td>{{ currentAssignment ?
                            'Currently sitting at seat ' ~ currentAssignment.getSeat() ~
                            ' from ' ~ from ~ ' ' ~
                            ' to ' ~ to ~ '.'
                            : 'Out of office' }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/person/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}People{% endblock %}

{% block body %}
    <div class="d-flex justify-content-center">
        <div class="col-md-8 mt-2">
            <h2 class="font-weight-bold bg-light rounded mx-auto text-center" style="opacity: 0.9;">
                People
            </h2>
            <form method="GET" action="{{ path('app_person') }}" class="mb-3 d-flex inline-search">
                <input type="text" name="search" class="form-control" placeholder="Search" value="{{ search_term }}" />
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            <div class="table-responsive" style="max-height: 70vh; overflow-y: auto;">
                <table class="modern-table">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Job Title</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for person in persons %}
                        <tr style="cursor:pointer" onclick="window.location='{{ path('app_person_detail', {'id': person.id}) }}'">
                            <td>{{ person.id }}</td>
                            <td>{{ person.firstName }}</td>
                            <td>{{ person.lastName }}</td>
                            <td>{{ person.email }}</td>
                            <td>{{ person.jobTitle }}</td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">No records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}